baseurl = "https://dekko.netlify.com/"
title = "dekko . arquitetura para todos"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "black"
  description = "arquitetura para todos"
  copyright = "&copy;2018 dekko . arquitetura para todos"
  sidebarAbout = [
    ""
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "ola@dekko.me"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "residencial e interiores"
  url = "residencial/"

  [[params.navlinks]]
  name = "comercial e corporativo"
  url = "comercial/"

  [[params.navlinks]]
  name = "patrimônio histórico"
  url = "patrimonio/"

  [[params.navlinks]]
  name = "design gráfico e com. visual"
  url = "comunicacao/"

  [[params.navlinks]]
  name = "institucional"
  url = "institucional/"

  [[params.navlinks]]
  name = "arquitetura efêmera"
  url = "efemera/"

  [[params.navlinks]]
  name = "urbanismo"
  url = "urbanismo/"

  [[params.navlinks2]]
  name = "sobre"
  url = "about/"

  [[params.navlinks2]]
  name = "contato"
  url = "contact/"

  [params.social]
  facebook      = "https://www.facebook.com/dekko.me"
  googleplus    = ""
  email         = "ola@dekko.me"
  twitter       = ""
  linkedin      = ""
  stackoverflow = ""
  instagram     = "http://www.instagram.com/dekko.me"
  github        = ""
